### ISSUE TITLE
Empty input?

### ISSUE THREAD

**Issue by Daijobou** [PitPik/tinyColorPicker#9] opened 2015-03-15 17:44 UTC
I have optional input fields to set a color or not to change the color. Its possible to clear the input field without colorPicker replace empty fields with his color-code after close?

**Comment by PitPik** [comment] 2015-03-16 09:50
You can always use a additional class name (like 'color no-update') and decide in your `renderCallback` what to do with it. You detect the class name and have an if fork to ignore this one...

**Comment by Daijobou** [comment] 2015-03-16 12:20
I do not know if I understand it correctly. renderCallback is used for click() change() and close(). I can set a class, yes. And I can check with $elm.hasClass('no-update') but how I can this check only for close the colorPicker?

I would like a event like http://api.jqueryui.com/autocomplete/#event-close that can handle this problem

But is this request not maybe a bug in first time?
- click on a input field and the colorpicker appear: fine!
- change in colorpicker the value and its change the input field to: fine!
- change directly the input field with another value, colorpicker accept this and change the background color of input field: fine!
- but when input field is cleared by user, why colorPicker insert again the old input with console error?:

```
Uncaught TypeError: undefined is not a function
```

Its not better to remove only input field styles and not change a valid users input?

Is there one needed reason to put the color code again in a cleared input field for close() event? My input fields starts all cleared. The user can insert code and save this setting. He should be able to undo ít. ;)

**Comment by Daijobou** [comment] 2015-03-16 12:39
I found a little trick, so this must be minimum one bug:
- Go to http://www.dematte.at/tinyColorPicker/
- click on first input field and clear input
- click now directly in next input field and the first input field is cleared, but style is not cleared.

one or both is a bug. ;)

**Comment by PitPik** [comment] 2015-03-16 14:28
Same here, this is not a bug but this behavior is not covered as I wouldn't see this as a needed feature. But you can always set a blur listener to the input fields, check for value and if empty then clear the background color

```
$('.color').colorPicker({...your options here...}).on('blur', function(){
    var $this = $(this);

    if ($this.val() === '') {
        $this.css({'background-color': ''});
    }
});
```

If I find a 'cheap' way to handle this then I'll put this inside color picker.

Thanks again

**Comment by Daijobou** [comment] 2015-03-16 16:23
That help me. Thanks! ;)

Can you tell me how I can stop colorPIcker to add color-code in a empty input field after close() colorPicker? I understand that he make rebuild background-color for custom input changes, but how I can stop this for empty input fields?

After clear input and close colorPicker I get this error:

```
Uncaught TypeError: undefined is not a function
```

**Comment by PitPik** [comment] 2015-03-17 14:00
This error is fixed with the latest commit.
For clearing field and setting background color to none use the 'blur' event I showed you earlier.
`$('.color').colorPicker().on('blur', 'input', function(){...do your stuff here});`

**Comment by Daijobou** [comment] 2015-03-17 16:00
After close colorPicker for a empty input field I get now "rgb(NaN,NaN,187)" ;)

@blur
I can change the background-color but how I can stop colorPicker to add rgb() text in that input field?
Example:

```
    $('input.colorbox').colorPicker().on('blur', function(){
        var $this = $(this);
console.log('test: '+$this.val());
        if ($this.val() === '') {
            $this.css({'background-color': ''});
        }
        $this.val('this will not overwrite the input field');
    });
```

The blur() coming up 2x times for each close.

console output:

```
test: 
test: rgb(NaN, NaN, 187)
```

**Comment by Daijobou** [comment] 2015-03-18 10:26
When you start or end with an empty input field, its going two times in render()

start because event: focusin and click is both called.
=> on('focus.a click.a', _selector, toggle).
maybe that is a option for optimize?
=> http://stackoverflow.com/a/9440580/706420

Next you use:

=> on('change.a', _selector, function() {
thats always called, with empty input field too. Not better to said only for "not empty" text? I remove the unnecessary _|| "rgb"_ because this make a new error for empty input fields:

```
on('change.a', _selector, function() {
    if (this.value) // <<<
    {
        _color.setColor(this.value);
        _instance.colorPicker.render();
    }
});
```

This stops the

```
Uncaught TypeError: undefined is not a function
```

and the new bug

```
rgb(NaN, NaN, 187)
```

The last problem with fill input field with old value. In toggle() you use:

```
        } else {
            $(_$UI).hide(_options.animationSpeed, function() {
                _$trigger.blur();
                _colorPicker.$trigger = null;
                preRender(false); // why?
            });
        }
```

Why you call here preRender(false)? After comment out this single line, all working fine. Maybe I missing something?

**Comment by PitPik** [comment] 2015-03-18 18:27
I just updated and committed a new version: Now there is a support for empty input fields. If input is empty and you press TAB key or you blur the colorPicker by clicking outside, the field stays empty and the background color defaults to none.

**Comment by Daijobou** [comment] 2015-03-18 18:42
Working great! You are the best!  Thank you very much. :+1: 

I love this simple stylish color-picker.

**Closed as completed** 2015-03-18 18:42 UTC
